version: '3.8'

services:
  web_wsp:
    build: .
    # ports:
    #   - "5000:5000"
    command: python __init__.py
    expose:
      - 93
    volumes:
      - ./app:/app/

  nginx_wsp:
    image: nginx:latest
    ports:
      - "140:80"
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=wsp.diego-luque.com
      - LETSENCRYPT_HOST=wsp.diego-luque.com
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web_wsp

networks:
  default:
    name: web_private_red_webapps
    external: true